chore(ssa refactor): Make abi generation completely deterministic in the function signature
noir-lang/noir pull request #1426
Opened 2023-05-27 14:58 UTC by kevaundray

# Description

Related to #1425 -- This means that Abi generation is completely determinsitic in the function signature. Instead of the return witnesses depending on the body of main.

## Problem\*

Resolves 

## Summary\*

This PR sets out to

### Example

Before:

```

```

After:

```

```

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

2023-05-27 16:24 UTC, kevaundray commented
Since the `distinct` keyword possibly applies constraints to enforce distinctness, this may make this unpleasant -- It depends on how we approach the initial issue of duplicated code in two places

2023-05-29 18:21 UTC, kevaundray commented
Converting to Draft as this is not high priority and we can come back to it once we implement the distinct keyword

2023-05-30 09:28 UTC, joss-aztec requested changes
To fix this implementation you would have to do something akin to reserving witness indices for the result, and then coming back to convert the corresponding values later.

2023-05-30 09:41 UTC, kevaundray commented on crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs
> -
We call `convert_ssa_value` in the `convert_ssa_return` so it should create the AcirVar if it does not exist. This is needed for things like when you just return a constant which would not have been defined before in the program and therefore not cached

2023-05-30 09:42 UTC, kevaundray commented
@joss-aztec Lets come back to this once distinct is implemented

2023-06-14 06:05 UTC, TomAFrench commented
I don't see how we can have both:
1. return witness indices are known prior to ACIR generation/optimization
2. redundant witnesses in the return values are merged.


Number 2. requires knowledge of the ACIR in order to determine whether we can tell if two witnesses are equal at compile-time. Are we then throwing this away in general rather than having the `distinct` keyword then?

2023-08-16 15:00 UTC, TomAFrench commented
@kevaundray are we ok to close this?

2023-08-21 22:23 UTC, closed without merging