chore: Implement checksum for cached CRS
noir-lang/noir pull request #1514
Opened 2023-06-03 14:18 UTC by vicyyn

# Description

Issue: https://github.com/noir-lang/noir/issues/1390

I added checksum integration for CRS. There are no details on how to implement so I did it in my own way. Thank you.

2023-06-05 22:33 UTC, phated requested changes
I'm pretty naive about what the Crc library you chose is doing. Where is the checksum being stored? I would expect it to be stored next to the CRS itself since nargo should/will create a cache directory for each backend.

2023-06-05 22:33 UTC, phated commented on crates/nargo_cli/src/cli/fs/common_reference_string.rs
> +                panic!("Common reference string checksum mismatch");
I believe we'd want to return an empty vector so the CRS will be fetched again since it was somehow corrupted.

2023-06-05 22:33 UTC, phated commented on crates/nargo_cli/src/cli/fs/common_reference_string.rs
> +            return Ok(common_reference_string);
The checksum storing should only happen during the filesystem write, I think.

2023-07-13 12:48 UTC, kevaundray commented
Closing as the issue that it is solving is no longer relevant

2023-07-13 12:48 UTC, closed without merging