chore!: Save witness in correct format that bb.js expects
noir-lang/noir pull request #1876
Opened 2023-07-06 14:49 UTC by vezenovm

# Description

We are moving to have our ACIR tests run in bb.js for proving and verification while nargo will just handle circuit execution.

## Problem\*

Resolves 

## Summary\*

This PR changes the format in which witnesses are saved to file. bberg is currently the only consumer of our witness output however this may be breaking for any old programs that still save the witness to file and use it elsewhere (however I see this as unlikely due to the large divergence in the TS bberg packages and Noir master). 

In order to be in line with bb.js we also need to enable the RecursiveAggregation opcode in acvm-backend-barretenberg as per this PR: https://github.com/noir-lang/acvm-backend-barretenberg/pull/225

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

2023-07-06 16:11 UTC, TomAFrench requested changes
This breaks any interop with the ACVM simulator. bb.js should update to accept the witness map format defined by ACIR.

2023-07-06 16:26 UTC, vezenovm commented
> This breaks any interop with the ACVM simulator. bb.js should update to accept the witness map format defined by ACIR.

Ah didn't realize this would break ACVM simulator. I switched this to a feature flag

2023-07-07 04:07 UTC, Savio-Sou commented
> bb.js should update to accept the witness map format defined by ACIR.

@TomAFrench could you open an issue for it on https://github.com/AztecProtocol/barretenberg/?

2023-07-07 10:22 UTC, kevaundray approved these changes

2023-07-07 10:38 UTC, merged

2023-07-10 07:04 UTC, TomAFrench commented
Reminder that we should not merge PRs which rely on patched versions of our own packages. This PR should have used the 0.6.1 release of `acvm-backend-barretenberg`.

Using a commit which wasn't in master for `acvm-backend-barretenberg` resulted in nightly releases failing and 0.8.0 failing on some targets.