chore: `nargo info` now prints information as a prettified table
noir-lang/noir pull request #2282
Opened 2023-08-11 10:37 UTC by Ethan-000

# Description

## Problem\*

Related to https://github.com/noir-lang/noir/issues/2089

## Summary\*

run `nargo info`

```rust
fn main(x : Field, y : pub Field) {
    assert(x * 2 == y * 3);
}

contract Foo {
    fn double(x: Field) -> pub Field { x * 2 }
    fn triple(x: Field) -> pub Field { x * 3 }
    internal fn quadruple(x: Field) -> pub Field { x * 4 }
    open internal fn skibbidy(x: Field) -> pub Field { x * 5 }
}

```

```rust
+----------+-----------+------------------------+--------------+----------------------+
| Contract | Function  | Language               | ACIR Opcodes | Backend Circuit Size |
+----------+-----------+------------------------+--------------+----------------------+
| Foo      | quadruple | PLONKCSat { width: 3 } | 1            | 2                    |
+----------+-----------+------------------------+--------------+----------------------+
| Foo      | double    | PLONKCSat { width: 3 } | 1            | 2                    |
+----------+-----------+------------------------+--------------+----------------------+
| Foo      | triple    | PLONKCSat { width: 3 } | 1            | 2                    |
+----------+-----------+------------------------+--------------+----------------------+
| Foo      | skibbidy  | PLONKCSat { width: 3 } | 1            | 1                    |
+----------+-----------+------------------------+--------------+----------------------+

```

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

2023-08-11 12:30 UTC, TomAFrench requested changes
Table looks good but you've made the `compile_success` integration tests must less strict.

2023-08-11 12:30 UTC, TomAFrench commented on crates/nargo_cli/build.rs
> +    cmd.assert().stdout(predicate::str::contains("ACIR Opcodes | Backend Circuit Size"));
This removes the point of this integration test which shows that the program is optimized down to an empty circuit.

2023-08-11 20:53 UTC, TomAFrench commented
Will review on Monday. Work life balance ser

2023-08-14 08:55 UTC, TomAFrench approved these changes

2023-08-14 09:00 UTC, TomAFrench commented
Currently if you use this in a workspace you get the output

```
+---------+------------------------+--------------+----------------------+
| Package | Language               | ACIR Opcodes | Backend Circuit Size |
+---------+------------------------+--------------+----------------------+
| a       | PLONKCSat { width: 3 } | 5            | 5                    |
+---------+------------------------+--------------+----------------------+
+---------+------------------------+--------------+----------------------+
| Package | Language               | ACIR Opcodes | Backend Circuit Size |
+---------+------------------------+--------------+----------------------+
| b       | PLONKCSat { width: 3 } | 5            | 5                    |
+---------+------------------------+--------------+----------------------+
```

Ideally this would be merged as so:

```
+---------+------------------------+--------------+----------------------+
| Package | Language               | ACIR Opcodes | Backend Circuit Size |
+---------+------------------------+--------------+----------------------+
| a       | PLONKCSat { width: 3 } | 5            | 5                    |
+---------+------------------------+--------------+----------------------+
| b       | PLONKCSat { width: 3 } | 5            | 5                    |
+---------+------------------------+--------------+----------------------+
```

Similarly we should collect contracts across different packages and collate them into the same table.

2023-08-14 09:01 UTC, TomAFrench requested changes
See comment

2023-08-14 09:20 UTC, kevaundray commented
> Currently if you use this in a workspace you get the output
> 
> ```
> +---------+------------------------+--------------+----------------------+
> | Package | Language               | ACIR Opcodes | Backend Circuit Size |
> +---------+------------------------+--------------+----------------------+
> | a       | PLONKCSat { width: 3 } | 5            | 5                    |
> +---------+------------------------+--------------+----------------------+
> +---------+------------------------+--------------+----------------------+
> | Package | Language               | ACIR Opcodes | Backend Circuit Size |
> +---------+------------------------+--------------+----------------------+
> | b       | PLONKCSat { width: 3 } | 5            | 5                    |
> +---------+------------------------+--------------+----------------------+
> ```
> 
> Ideally this would be merged as so:
> 
> ```
> +---------+------------------------+--------------+----------------------+
> | Package | Language               | ACIR Opcodes | Backend Circuit Size |
> +---------+------------------------+--------------+----------------------+
> | a       | PLONKCSat { width: 3 } | 5            | 5                    |
> +---------+------------------------+--------------+----------------------+
> | b       | PLONKCSat { width: 3 } | 5            | 5                    |
> +---------+------------------------+--------------+----------------------+
> ```
> 
> Similarly we should collect contracts across different packages and collate them into the same table.

Why do we want this to be merged?

2023-08-14 11:14 UTC, kevaundray commented
> now print something like this 😂
> <img alt="with color" width="557" src="https://user-images.githubusercontent.com/70556667/260417652-9bf914ae-8f04-4a85-b609-c72dc8f3c7ed.png">

How does this print for contracts?

2023-08-14 11:14 UTC, kevaundray commented
> I suppose depends on whether in a workspace, can different packages be compiled to different languages?

I think its a matter of preference, so rationale for preferences would be good

2023-08-14 12:02 UTC, TomAFrench approved these changes
LGTM

2023-08-14 12:19 UTC, kevaundray commented
oof sorry @TomAFrench seems there was a race condition with changing the PR title 😁

2023-08-14 12:30 UTC, merged