Mimc sponge
noir-lang/noir pull request #2297
Opened 2023-08-12 05:53 UTC by seugu

# Description

## Problem\*

Resolves 

## Summary\*

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

2023-08-14 09:26 UTC, kevaundray commented
Hi, 

Thank you for your contribution!

Can you update the description to accurately describe the changes being made in this PR, ie why files were moved, why we need the sponge variation etc?

2023-08-15 09:21 UTC, TomAFrench requested changes
This is currently a breaking change. Can you please undo moving the existing mimc functions?

2023-08-15 10:04 UTC, kevaundray commented
> This is currently a breaking change. Can you please undo moving the existing mimc functions?

Perhaps its better to just change the PR title because it makes sense to move it to its own file

2023-08-15 19:02 UTC, vezenovm commented
@TomAFrench I changed to a breaking change as I do think moving the mimc functions to their own file makes sense. Especially when they have lots of constant that are needed for the impl

2023-08-31 16:10 UTC, vezenovm commented on noir_stdlib/src/hash/mimc.nr
> +    let constant: [Field; 218] = [
Is this the same constants list as in Feistel decryption? Could we move it to a global?

2023-08-31 16:11 UTC, vezenovm commented on noir_stdlib/src/hash/mimc.nr
> +    let constant: [Field; 218] = [
Is this the same constants list as Feistel decryption? If so could we move it to a global?

2023-08-31 16:11 UTC, vezenovm commented on noir_stdlib/src/hash/mimc.nr
> +    let constant: [Field; 218] = [
Ideally at the bottom of the file so that we can see the algorithm implementations first

2023-08-31 16:13 UTC, vezenovm commented on noir_stdlib/src/hash/mimc.nr
> +    let constants: [Field; MIMC_BN254_ROUNDS] = [
I believe we should be able to move these constants out of the func as well. These can be `mimc_bn254_constants` and the others `mimc_feistel_constants` or something similar

2023-09-05 19:31 UTC, vezenovm commented on noir_stdlib/src/hash/mimc.nr
> +      global mimc_feistel_constants: [Field; MIMC_FEISTEL_ROUNDS] = [
```suggestion
global mimc_feistel_constants: [Field; MIMC_FEISTEL_ROUNDS] = [
```

2023-09-05 19:31 UTC, vezenovm commented on noir_stdlib/src/hash/mimc.nr
> +    //generated from seed "mimc" using keccak256
```suggestion
```

2023-09-05 19:31 UTC, vezenovm commented on noir_stdlib/src/hash/mimc.nr
> +
```suggestion
```

2023-09-05 19:31 UTC, vezenovm commented on noir_stdlib/src/hash/mimc.nr
> +
```suggestion
//generated from seed "mimc" using keccak256 
```

2023-09-05 19:35 UTC, TomAFrench commented
I can't really validate the correctness of the implementation so I'll approve if someone on the team vouches for it.

That said, I think this goes against our aims in #1258. This would be best as a mimc library.

2023-09-05 20:00 UTC, vezenovm commented
> That said, I think this goes against our aims in #1258. This would be best as a mimc library.

I recommended for this to be put in the standard lib as MiMC is common hash function that should not be changing much and we already have MiMC7 inside of the stdlib. I forgot about the issue and aims listed in #1258, but perhaps this can just be moved out once we have some type of `hashes` library under noir-lang. If we feel strongly this should remain outside of Noir, we can ask @seugu to turn his Noir-MiMCSponge repo into a library. 

The implementation is correct from my review and checks against the circom implementations.

2023-09-05 20:04 UTC, vezenovm commented
@seugu It looks like you are using an old version of `nargo` for the new tests you included under `execution_success`. The projects are missing the `name` and `type` fields in the `Nargo.toml`.

2024-09-26 13:26 UTC, TomAFrench commented
I'm closing this PR as the mimc implementation has been moved to an external library: https://github.com/noir-lang/mimc

2024-09-26 13:26 UTC, closed without merging