feat: Add trait definition representation in DefCollector and HIR
noir-lang/noir pull request #2338
Opened 2023-08-16 10:44 UTC by yordanmadzhunkov

# Description
This is the next PR from the series of Trait Implementation. I expected to be merged quickly, because it's some simple definition that will be used later

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

2023-08-16 11:18 UTC, yordanmadzhunkov commented
@jfecher

2023-08-16 11:21 UTC, TomAFrench reviewed
~~Removing unrelated changes~~ Ah looks like I can't make changes to this PR as it's on a fork.

2023-08-16 11:21 UTC, TomAFrench commented on crates/noirc_frontend/src/hir/resolution/import.rs
>          }
```suggestion
        }

```

2023-08-16 11:21 UTC, TomAFrench commented on crates/noirc_frontend/src/hir/resolution/import.rs
>          }
```suggestion
        }

```

2023-08-16 11:21 UTC, TomAFrench commented on crates/noirc_frontend/src/hir/resolution/import.rs
> +
```suggestion
        let found_ns = current_mod.find_name(segment);
```

2023-08-16 13:11 UTC, jfecher requested changes
Looks good. We can merge once `Type::Trait` is removed.

2023-08-17 14:19 UTC, jfecher approved these changes
I'm approving this to keep development speed high, but lets move the Trait struct to its own file (hir_def/traits?) and update the comment/type on the `traits` field of the NodeInterner as part of a later PR.

2023-08-17 14:19 UTC, jfecher commented on crates/noirc_frontend/src/node_interner.rs
> +    // We'd just lookup their methods as needed through the NodeInterner.
Noting that traits are not shared across multiple type nodes anymore and this TODO likely applies now

2023-08-17 17:18 UTC, merged