fix: correct off-by-one errors in lexer spans
noir-lang/noir pull request #2393
Opened 2023-08-21 23:03 UTC by TomAFrench

# Description

## Problem\*

Resolves #1682 

## Summary\*

This PR addresses the off-by-one errors in how we deal with spans in a way which makes sense to me.

For example in `parse_block_comment` we're creating a span which goes from the start of the comment to the very last character in the file. We should then have an inclusive span here. Similarly when we have a `&&` we were previously creating a span of size 1 which doesn't really make sense for when we're capturing two characters.

Based on this, I noticed that `from_position` was creating exclusive end spans whereas we're calling it in the same where were logically we should have inclusive spans. I then switched this and the red squigglies are all appearing where I expect them to be.

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

2023-08-21 23:12 UTC, phated reviewed
I'll give this a try in a bit

2023-08-22 10:36 UTC, TomAFrench commented on crates/noirc_frontend/src/lexer/lexer.rs
> -        let span = Span::new(self.position..self.position + 1);
This is a change to how we display this error. Previously we'd only show a red squiggly over the first `*` of the comment but now we go from that `*` to the end of the file.

Motivation being that it's more noticeable and fits better with a "hey your comment is covering everything" error.

2023-08-22 16:36 UTC, jfecher submitted a review, later dismissed

2023-08-22 22:20 UTC, phated requested changes
<img width="290" alt="Screenshot 2023-08-22 at 3 19 30 PM" src="https://github.com/noir-lang/noir/assets/992373/a0a44eb6-aa47-46d3-af0d-a15ffc719558">

I found more span problems even with these changes included. I'll push up my changes shortly

2023-08-22 22:25 UTC, phated commented
Two more issues with strings:
<img width="217" alt="Screenshot 2023-08-22 at 3 25 19 PM" src="https://github.com/noir-lang/noir/assets/992373/d9b65bbc-3ce4-4d18-b845-4605b63143f0">

2023-08-22 22:27 UTC, phated commented
Pushed my new changes that fix all of the above:
<img width="296" alt="Screenshot 2023-08-22 at 3 26 11 PM" src="https://github.com/noir-lang/noir/assets/992373/8cf3ede5-219b-4ac8-b898-e00aa02f3f32">

2023-08-22 22:29 UTC, phated approved these changes
Approving, but I made changes so let's get other feedback

2023-08-24 14:08 UTC, jfecher approved these changes
LGTM. If any more off by one spans are found we can fix them as part of another PR

2023-08-24 15:12 UTC, merged