chore(noir): Release 0.11.0
noir-lang/noir pull request #2496
Opened 2023-08-30 19:48 UTC by kevaundray

:robot: I have created a release *beep* *boop*
---

## [0.11.0](https://github.com/noir-lang/noir/compare/v0.10.5...v0.11.0) (2023-08-30)

### ⚠ BREAKING CHANGES

* Remove keys from preprocessed artifacts ([#2283](https://github.com/noir-lang/noir/issues/2283))

### Miscellaneous Chores

* Remove keys from preprocessed artifacts ([#2283](https://github.com/noir-lang/noir/issues/2283)) ([4554287](https://github.com/noir-lang/noir/commit/45542870c85ff59487ad14c25f3e1d6692623644))

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

2023-09-04 21:50 UTC, TomAFrench reviewed
Blocking for https://github.com/noir-lang/noir/pull/2558 to avoid churn on CRS location.

2023-09-04 21:50 UTC, TomAFrench requested changes
~above~ This has been addressed now so this review can be dismissed.

2023-09-07 12:51 UTC, TomAFrench approved these changes

2023-09-07 13:13 UTC, merged

2023-09-07 13:14 UTC, kevaundray commented
:robot: Release is at https://github.com/noir-lang/noir/releases/tag/v0.11.0 :sunflower: