fix(ssa): Do not simplify ArrayLen for slices in SSA
noir-lang/noir pull request #2647
Opened 2023-09-11 22:33 UTC by vezenovm

# Description

## Problem\*

Resolves #2645 

## Summary\*

We reuse the same value to represent a slice length throughout the SSA. This can lead to bugs due to that some other SSA optimization rely on SSA having unique values, such as replacing previously constrained values during constant folding. Perhaps we can implement a strategy to use different values in different locations for slice lengths, but that is a larger workaround. 

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

2023-09-12 15:56 UTC, TomAFrench commented on compiler/noirc_evaluator/src/ssa/opt/constant_folding.rs
> +        side_effects_enabled: &bool,
```suggestion
        side_effects_enabled: bool,
```

Let's dereference this boolean earlier

2023-09-15 17:22 UTC, kevaundray commented on compiler/noirc_evaluator/src/ssa/opt/constant_folding.rs
> +        println!("ssa: {ssa}");
```suggestion
```

2023-09-15 17:23 UTC, kevaundray submitted a review, later dismissed

2023-09-15 17:24 UTC, kevaundray commented
Could you resolve the merge conflicts por favor?

2023-09-19 18:34 UTC, vezenovm commented
Conflicts resolved this is ready for review again

2023-09-20 21:11 UTC, jfecher requested changes
I think this PR is too pessimistic. Since the default value of enable side effects is true, this can effectively disable constant folding for an entire program (after the first `if` when enable_side_effects is first inserted). I think a better solution would be finding the side-effectful instructions that may differ depending on the status of `enable_side_effects` and selectively disabling those.

2023-09-20 21:11 UTC, jfecher commented on compiler/noirc_evaluator/src/ssa/opt/constant_folding.rs
> +        let mut side_effects_enabled: bool = false;
```suggestion
        let mut side_effects_enabled = false;
```

2023-09-21 14:42 UTC, vezenovm commented
> Since the default value of enable side effects is true, this can effectively disable constant folding for an entire program

I will take a look at how I can select specific instructions. Although, this PR wouldn't disable constant folding for an entire program, it would just disable usage of the constrain statement cache and replacing those values.

2023-09-21 14:49 UTC, vezenovm commented
> I think a better solution would be finding the side-effectful instructions that may differ depending on the status of `enable_side_effects` and selectively disabling those.

Actually I think because this only disables the constrain cache this PR does do what this says by only disabling folding the dynamic part of a constrain instruction.

2023-09-21 18:01 UTC, vezenovm commented
I have updated this PR to remove the constrain cache inside of constant folding. Reasoning for this can be found in the PR description.

2023-09-21 20:21 UTC, jfecher approved these changes

2023-09-21 20:34 UTC, merged