chore!: update to bb.js version 0.7.3
noir-lang/noir pull request #2729
Opened 2023-09-15 18:50 UTC by kevaundray

# Description

Updates bb to 0.7.3

## Problem\*

Resolves 

## Summary\*

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

2023-09-15 18:54 UTC, vezenovm submitted a review, later dismissed

2023-09-15 18:59 UTC, kevaundray commented
Note, we know that 0.6.7 works and checking the changelog, the breaking change that happened between then and 0.7.3 was an aztec-packages renaming. See [here](https://github.com/AztecProtocol/aztec-packages/blob/master/CHANGELOG.md#067-2023-09-11)

2023-09-15 22:23 UTC, TomAFrench requested changes
This release does not exist https://github.com/AztecProtocol/aztec-packages/issues/2347

2023-09-28 19:42 UTC, TomAFrench approved these changes

2023-09-28 22:30 UTC, merged