chore(docs): Supplement descriptions for default integers being `u64`
noir-lang/noir pull request #3237
Opened 2023-10-20 19:50 UTC by Savio-Sou

# Description

## Summary\*

Following https://github.com/noir-lang/noir/pull/2764 and https://github.com/noir-lang/docs/commit/7bb178db5f3d470130aea0d393053ae3165664be, this PR:
- Removes the mentioning of `Field` as the default integer type from the "Fields" doc page
- Adds description of `u64` being the default integer type in the "Integers" doc page
- Slightly reformatted the "Integers" doc page

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

2023-10-21 14:58 UTC, kevaundray commented
If you do not supply a type for an integer in Noir, it would not default to u64 -- The PRs that were linked were referring to the index of a for loop

2023-10-23 22:58 UTC, Savio-Sou commented
Oh hmm, so we now have different integer type defaults under different scenarios?

Sounds like that could get troublesome.

2023-10-24 21:55 UTC, signorecello approved these changes

2023-10-24 22:06 UTC, TomAFrench requested changes
These docs are inaccurate as mentioned in above messages.

2023-10-25 17:05 UTC, Savio-Sou commented on docs/docs/language_concepts/data_types/01_integers.md
> +> **Note:** When an integer is defined in Noir without a specific type, it would default to `u64`.
Does it apply to array indices as well? (Seemed like so from the descriptions in https://github.com/noir-lang/noir/pull/2764.)

2023-10-25 20:05 UTC, Savio-Sou commented on docs/docs/language_concepts/data_types/01_integers.md
> +> **Note:** When an integer is defined in Noir without a specific type, it would default to `u64`.
🙏

2023-10-25 20:08 UTC, Savio-Sou commented
PR revised with Jake's suggestions incorporated.

2023-10-25 20:41 UTC, jfecher approved these changes
LGTM

2023-10-26 14:20 UTC, TomAFrench approved these changes

2023-10-26 14:47 UTC, merged