Auto return
noir-lang/noir pull request #360
Opened 2022-10-05 10:28 UTC by guipublic

With this PR, prover does not need to provide the main return value and can instead write in the prover.toml:
`return = ""`

Note that the return parameter must still be present in prover.toml, but we can give an empty value instead using an empty string.
Generating the proof will also create the verifier.toml (it overwrites if already  existing) with the public inputs (including the return value if there is one) corresponding to the provided prover.toml.

Here is a bit of context:
The `main()` function of a noir program can return a public value, which is computed by this noir program.
However, this public value is also a public input for the ZK proof so this requires the prover to compute by itself the value and put it in the provel.toml in order to generate the proof.
But the computation itself can be delicate if the noir program is doing a lof of (e.g. cryptographic) stuff. On the other hand, generating a proof of execution is also executing the program so noir should have already computed this value and it should not be necessary for the prover to provide the main return value.
This follows the concerns expressed in issue 355 [https://github.com/noir-lang/noir/issues/355]

2022-10-05 15:25 UTC, jfecher commented
So when we have `return = ""` in the prover.toml it is now expected to write the actual return value into the Verifier.toml and create the file if it doesn't currently exist, correct? Does it rewrite the prover.toml with the correct return value as well?

2022-10-05 16:05 UTC, guipublic commented
In all cases (i.e with a return="" , or with return="5", or with no return at all), it now generates the verifier.toml, and overwrites existing file.
The correct value will be in the verifier.toml, if there is a return value, whether or not it is specified in the prover.toml
- The prover.toml is never changed.
- The verifier.toml is always generated during **prove**
- The verifier.toml is never modified during **verify**

2022-10-05 17:01 UTC, jfecher requested changes

2022-10-07 19:56 UTC, guipublic commented on crates/nargo/src/cli/prove_cmd.rs
> +        abi.parameters.iter().position(|x| x.0 == NodeInterner::main_return_name())
Thanks, it's done

2022-10-07 19:57 UTC, guipublic commented on crates/nargo/src/cli/prove_cmd.rs
> +                    index += 1
Indeed the new witness is useless

2022-10-07 19:58 UTC, guipublic commented on crates/nargo/src/cli/prove_cmd.rs
> +                                *solved_witness.get(&Witness::new(w_ret.0 + i as u32)).unwrap(),
Done

2022-10-09 15:51 UTC, guipublic commented
Undefined arrays returned from main does not work, so I return an error in that case.
I will fix this issue in a separate PR.

2022-10-10 17:45 UTC, vezenovm approved these changes

2022-10-11 13:37 UTC, jfecher commented on crates/nargo/src/cli/prove_cmd.rs
> +                                *solved_witness.get(&Witness::new(w_ret.0 + i as u32)).unwrap(),
Actually, can it be simplified further to `solved_witness[&Witness::new(w_ret.0 + i as u32)]`?

2022-10-12 13:07 UTC, jfecher approved these changes

2022-10-14 22:44 UTC, merged