chore: Release Noir()
noir-lang/noir pull request #3862
Opened 2023-12-19 00:11 UTC by kevaundray

:robot: I have created a release *beep* *boop*
---

<details><summary>0.39.0</summary>

## [0.39.0](https://github.com/noir-lang/noir/compare/v0.38.0...v0.39.0) (2023-12-19)

### ⚠ BREAKING CHANGES

* Remove unused methods on ACIR opcodes ([#3841](https://github.com/noir-lang/noir/issues/3841))
* Remove partial backend feature ([#3805](https://github.com/noir-lang/noir/issues/3805))

### Features

* Aztec-packages ([#3754](https://github.com/noir-lang/noir/issues/3754)) ([c043265](https://github.com/noir-lang/noir/commit/c043265e550b59bd4296504826fe15d3ce3e9ad2))
* Speed up transformation of debug messages ([#3815](https://github.com/noir-lang/noir/issues/3815)) ([2a8af1e](https://github.com/noir-lang/noir/commit/2a8af1e4141ffff61547ee1c2837a6392bd5db48))

### Bug Fixes

* Deserialize odd length hex literals ([#3747](https://github.com/noir-lang/noir/issues/3747)) ([4000fb2](https://github.com/noir-lang/noir/commit/4000fb279221eb07187d657bfaa7f1c7b311abf2))

### Miscellaneous Chores

* Remove partial backend feature ([#3805](https://github.com/noir-lang/noir/issues/3805)) ([0383100](https://github.com/noir-lang/noir/commit/0383100853a80a5b28b797cdfeae0d271f1b7805))
* Remove unused methods on ACIR opcodes ([#3841](https://github.com/noir-lang/noir/issues/3841)) ([9e5d0e8](https://github.com/noir-lang/noir/commit/9e5d0e813d61a0bfb5ee68174ed287c5a20f1579))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

2024-01-10 01:06 UTC, TomAFrench requested changes
Need to make more breaking changes so blocking this in the short term.

2024-01-17 16:28 UTC, Savio-Sou approved these changes

2024-01-17 16:35 UTC, TomAFrench commented
Tests are currently failing and so needs to be fixed.

2024-01-22 14:48 UTC, TomAFrench approved these changes

2024-01-22 15:34 UTC, merged

2024-01-22 15:34 UTC, kevaundray commented
:robot: Release is at https://github.com/noir-lang/noir/releases/tag/v0.23.0 :sunflower: