add `nargoup` installation script
noir-lang/noir pull request #418
Opened 2022-10-25 23:57 UTC by TomAFrench

# Related issue(s)

closes #417

# Description

## Summary of changes

This PR adds the `nargoup` script from https://github.com/TomAFrench/nargoup.

This is basically a copy-paste of https://github.com/foundry-rs/foundry/tree/master/foundryup with the following changes:
- We don't show the message for mac users to install libusb
- We always build from source rather than attempting to download a binary

`nargoup` is just a placeholder name so we may want to consider others such as `noirup`, etc.

Once this PR is approved, we'll want to make another PR to the noir book updating the installation instructions to point people towards nargoup

Aztec may also want to point a nicer url at the `install` script so people could do `curl -L https://nargo.aztec.network | bash` similarly to how you can do `curl -L https://foundry.paradigm.xyz | bash` for foundry.

## Dependency additions / changes

N/A

## Test additions / changes

N/A

# Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [x] I have reviewed the changes on GitHub, line by line.
- [x] I have ensured all changes are covered in the description.

2022-10-26 15:59 UTC, kevaundray submitted a review, later dismissed

2022-10-28 10:28 UTC, guipublic commented
Could you rather use 'noirup' instead of 'nargoup' for the name?
Nargoup is a bit of a weird sound. Plus for rust the name is rustup, not cargoup.

2022-10-28 10:30 UTC, guipublic requested changes
Could you rather use 'noirup' instead of 'nargoup' for the name?
Nargoup is a bit of a weird sound. Plus for rust the name is rustup, not cargoup.

2022-10-29 00:43 UTC, TomAFrench commented
> Could you rather use 'noirup' instead of 'nargoup' for the name? Nargoup is a bit of a weird sound. Plus for rust the name is rustup, not cargoup.

Yeah, I'm happy to change this. `nargoup` looks a bit "goopy" imo so I was a bit hesitant to have it as the main update command.

I'll likely keep `.nargo` as the dir and all the variable names just just rename the bash file from `nargoup` up to `noirup`

2022-10-31 18:30 UTC, kevaundray approved these changes

2022-11-02 09:11 UTC, guipublic approved these changes

2022-11-09 14:58 UTC, merged