Add `else if` syntactic sugar
noir-lang/noir pull request #421
Opened 2022-10-31 01:31 UTC by TomAFrench

# Related issue(s)

Closes #420

# Description

## Summary of changes

This PR makes the `if_expr` parser recursive so that we can support chains of `else if` statements as described in #420.

Currently draft as I get stack overflow issues on the 3rd `if` statement. i.e.

```
if a == c[0] {
    constrain c[0] == 0;
} else if a == c[1] {
    constrain c[1] == 0;
} else {
    constrain c[2] == 0;
}
```

compiles and proves correctly, whereas

```
if a == c[0] {
    constrain c[0] == 0;
} else if a == c[1] {
    constrain c[1] == 0;
} else if a == c[2] {
    constrain c[2] == 0;
}
```

fails with a stack overflow error.

The explicit wrapping in a block expression seems unnecessary but doesn't hurt for now.

## Dependency additions / changes

N/A

## Test additions / changes

(If applicable.)

# Checklist

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [ ] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [ ] I have reviewed the changes on GitHub, line by line.
- [ ] I have ensured all changes are covered in the description.

# Additional context

(If applicable.)

2022-11-01 13:56 UTC, jfecher commented
The parser code looks correct to me. The stack overflow is happening at `acvm::PartialWitnessGenerator::solve:193`, recurring on just that one line with 8 unsolved gates.

2022-11-01 22:14 UTC, TomAFrench commented
Thanks for taking a look. I don't really understand what's going in that function so I probably won't be able to make meaningful progress on this as it stands.

2022-11-03 13:26 UTC, jfecher commented
A fix was just merged for this, try testing again to see if it works now

2022-11-03 14:10 UTC, TomAFrench commented
Looks good. I can prove and verify the program in `if_else_chain` now.

Thanks for the help with this.

2022-11-03 16:22 UTC, guipublic requested changes
It's fine for me, could you just remove Verifier.toml from the test? We are getting rid of them since they are auto-generated.

2022-11-03 17:26 UTC, guipublic approved these changes

2022-11-03 17:27 UTC, jfecher approved these changes

2022-11-07 19:10 UTC, merged