feat: Sync from aztec-packages
noir-lang/noir pull request #4341
Opened 2024-02-12 14:28 UTC by AztecBot

BEGIN_COMMIT_OVERRIDE
chore: Pull noir (https://github.com/AztecProtocol/aztec-packages/pull/4546)
feat: Added cast opcode and cast calldata (https://github.com/AztecProtocol/aztec-packages/pull/4423)
refactor: cleanup of `abi.nr` in `aztec-nr` (https://github.com/AztecProtocol/aztec-packages/pull/4473)
END_COMMIT_OVERRIDE

2024-02-12 14:45 UTC, TomAFrench requested changes
No real objections to this. Just making sure this doesn't go in before we have a `bb` release containing this serialisation code as @Savio-Sou wants to make a Noir release soon.

2024-02-12 21:55 UTC, Savio-Sou commented
Thanks Tom. Noir v0.24.0 is now pre-released.

2024-02-13 13:33 UTC, sirasistant approved these changes

2024-02-13 13:36 UTC, TomAFrench approved these changes

2024-02-13 13:46 UTC, merged