chore: Add #[recursive] Explainer to Documentation
noir-lang/noir pull request #4399
Opened 2024-02-16 18:09 UTC by paulallensuxs

# Description

## Problem

Step towards [#4392](https://github.com/noir-lang/noir/issues/4392)

The documentation for Recursive Proofs was lacking information on the newly introduced `#[recursive]` attribute, which is crucial for understanding how to mark circuits for recursive proof generation. 

## Summary

This pull request updates the Recursive Proofs documentation page to include a comprehensive section on the `#[recursive]` attribute. It explains the attribute's purpose, how it should be used, and provides an example demonstrating its application within a circuit definition. 

## Additional Context

The introduction of the `#[recursive]` attribute simplifies the process of designating circuits for recursive proofs, eliminating the need for manual flagging in the tooling infrastructure. 

## Documentation

- [ ] No documentation needed.
- [x] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

2024-02-21 00:05 UTC, signorecello requested changes
Thanks @paulallensuxs I'd just add this change to the `versioned_docs`, namely under the `v0.24.0` version as specified in the issue.

This will make the doc change available for 0.24.0 which is when the change was introduced.

2024-02-21 15:51 UTC, signorecello approved these changes
Thanks!

2024-02-22 12:33 UTC, Savio-Sou reviewed
Thank you for submitting the PR!

Minor nits:

2024-02-22 12:33 UTC, Savio-Sou commented on docs/docs/noir/standard_library/recursion.md
> +By incorporating this attribute directly in the circuit's definition, tooling like Nargo and NoirJS can automatically handle the proving of recursive Noir programs without requiring additional flags
```suggestion
By incorporating this attribute directly in the circuit's definition, tooling like Nargo and NoirJS can automatically execute recursive-specific duties for Noir programs (e.g. recursive-friendly proof artifact generation) without additional flags or configurations.
```

We are currently aiming for automation in artifacts generation, but not necessarily proving + recursive verification yet as we would need a generalized workflow that could support different forms of recursive proving.

Additional context: https://github.com/noir-lang/noir/issues/4336#issuecomment-1938767144

2024-02-22 12:33 UTC, Savio-Sou commented on docs/versioned_docs/version-v0.24.0/noir/standard_library/recursion.md
> +By incorporating this attribute directly in the circuit's definition, tooling like Nargo and NoirJS can automatically handle the proving of recursive Noir programs without requiring additional flags
```suggestion
By incorporating this attribute directly in the circuit's definition, tooling like Nargo and NoirJS can automatically execute recursive-specific duties for Noir programs (e.g. recursive-friendly proof artifact generation) without additional flags or configurations.
```

2024-02-22 12:57 UTC, merged