Refactor stdlib into a separate noir library
noir-lang/noir pull request #443
Opened 2022-11-05 13:21 UTC by ilitteri

# Related issue(s)

Resolves #423 

# Description

## Summary of changes

This PR abstracts the driver from the stdlib addition and moves the stdlib as a standalone nargo crate to the package manager level and when nargo is installed it is copied to the native config dir for the driver to look up to when adding it as an implicit dependency when crating a new project.

## Dependency additions / changes

`dirs` is added as a `build-dependency` in `nargo`.

# Checklist

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [ ] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [ ] I have reviewed the changes on GitHub, line by line.
- [ ] I have ensured all changes are covered in the description.

# Additional context

N/A

2022-11-05 14:38 UTC, kevaundray commented on crates/nargo/src/cli/mod.rs
> +// FIXME: I not sure that this is the right place for this tests.
Can you open an issue to track this TODO?

2022-11-05 14:41 UTC, kevaundray commented on crates/noirc_driver/src/lib.rs
> +    // NOTE: Maybe build could be skipped given that now it is a pass through method.
Can you open an issue for this to track discussion?

2022-11-05 14:43 UTC, kevaundray requested changes
LGTM. Just a few comments on creating tracking issues for some TODOs

2022-11-07 10:30 UTC, guipublic reviewed
I don't understand the purpose of this PR, and in particular having the std_lib not been a standalone crate anymore does not seem a good move to me.

2022-11-07 17:56 UTC, guipublic commented
> I don't understand the purpose of this PR, and in particular having the std_lib not been a standalone crate anymore does not seem a good move to me.

We had an internal discussion and what I got from it is that the purpose of the PR is to removing dependency on the rust compiler for the std::lib, so that we do not need additional installation steps for instance.
However we agreed not to move it to a Nargo subdirectory, keep it on top-level but remove it from the compiler directory and have it managed by Nargo like you did.

2022-11-07 18:27 UTC, ilitteri commented
> > I don't understand the purpose of this PR, and in particular having the std_lib not been a standalone crate anymore does not seem a good move to me.
> 
> We had an internal discussion and what I got from it is that the purpose of the PR is to removing dependency on the rust compiler for the std::lib, so that we do not need additional installation steps for instance. However we agreed not to move it to a Nargo subdirectory, keep it on top-level but remove it from the compiler directory and have it managed by Nargo like you did.

Great! Let me know if more changes are needed, I'll be glad to make them.

2022-11-08 17:16 UTC, kevaundray approved these changes

2022-11-08 17:16 UTC, merged