Make `noirup` pull latest nightly build by default
noir-lang/noir pull request #470
Opened 2022-11-14 23:19 UTC by TomAFrench

# Related issue(s)

https://github.com/noir-lang/noir/issues/225 Releases don't contain binaries anymore

# Description

## Summary of changes

`noirup` currently always builds `nargo` from source due to #225. As we move towards publishing binaries we can have `noirup` take advantage of this to pull the nightly build.

This PR makes this the default behaviour for `noirup`. The current behaviour of building locally is still available through `noirup -b master`.

I haven't tested this yet as there are currently no binaries to download but we can test tomorrow.

## Dependency additions / changes

N/A

## Test additions / changes

N/A

# Checklist

- [ ] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [ ] I have reviewed the changes on GitHub, line by line.
- [x] I have ensured all changes are covered in the description.

# Additional context

(If applicable.)

2022-11-17 10:30 UTC, TomAFrench commented
Keep in mind that there's currently no build for `apple-darwin` on the nightly release tag so `noirup` will fail until that exists.

2022-11-28 15:46 UTC, jfecher reviewed
Pinging @kobyhallx for tooling visibility

2022-11-28 15:46 UTC, jfecher commented on noirup/noirup
> +    ARCHITECTURE="x86_64"
Can we give an error message if the user is not using an x86_64 system? I'd rather an explicit error here than a more confusing one later on.

2022-12-01 13:27 UTC, kobyhallx requested changes

2022-12-01 13:27 UTC, kobyhallx commented on noirup/noirup
> +CONFIG_DIR=${XDG_CONFIG_HOME-"$HOME/.config"}
This location is only valid for Linux, on darwin it will failr as it expects `$HOME/Library/Application Support`

2022-12-01 13:27 UTC, kobyhallx commented on noirup/noirup
> +    # We currently only provide binaries targetting x64_64 architectures.
We've started providing other architectures, it would be good to include them as well

2022-12-05 10:53 UTC, kobyhallx approved these changes

2022-12-05 10:53 UTC, kobyhallx commented
Merging with intent to move noirup into its own repository.

2022-12-05 10:54 UTC, merged