feat: arithmetic generics
noir-lang/noir pull request #5060
Opened 2024-05-21 14:58 UTC by michaeljklein

# Description

## Problem\*

Supersedes https://github.com/noir-lang/noir/pull/4958

## Summary\*

- keeping variables up to date in the other approach was too heavy
- this approach interns the arithmetic part so that a generic arithmetic expression can be represented as:
```
(id_to_expr_with_holes, Vec<variable_in_expr>)
```

## Additional Context

Remaining issues:
- https://github.com/noir-lang/noir/issues/5149
- https://github.com/noir-lang/noir/issues/5150
- https://github.com/noir-lang/noir/issues/5151
- https://github.com/noir-lang/noir/issues/5153

## Documentation\*

Check one:
- [ ] No documentation needed.
- [ ] Documentation included in this PR.
- [x] **[For Experimental Features]** Documentation to be submitted in a separate PR. (https://github.com/noir-lang/noir/issues/5151)

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

2024-05-21 16:27 UTC, jfecher reviewed
Initial approach looks good, nothing really jumped out at me

2024-05-21 16:27 UTC, jfecher commented on compiler/noirc_frontend/src/node_interner.rs
> +    Variable(Rc<String>),
Should probably keep at least the type variable id if not the whole type variable here eventually, right? To differentiate identical names if needed.

2024-05-31 14:39 UTC, vezenovm commented on test_programs/execution_success/generic_arith/src/main.nr
> +    // assert(tail::<Field, 3>([1,2,3]) == [2, 3]);
Does this line and the other commented out assertions also pass in the elaborator?

2024-05-31 16:38 UTC, jfecher requested changes
I'm hesitant on the approach here and want to hold off on merging for now.

The use of interning bloats the code a bit and it's unclear to me why we need to intern every constant used in a type position for example. I would have thought we'd only need to remember arith expressions that are unified against each other.

I also think delaying these type checks until monomorphization will probably introduce bugs that are difficult/impossible to fix without changing the approach.

I'm thinking now maybe we should just admit we're adding dependent types to Noir and try to add unification / checking for those directly. We may need to switch to a bidirectional type checker but I think it'd end up being the cleaner approach in the end and could let us eventually handle traits as well.

2024-05-31 17:05 UTC, michaeljklein commented on compiler/noirc_frontend/src/hir_def/types.rs
> +            Type::GenericArith(arith_id, generics) => {
Need a TODO: this prints the arith ID

2024-06-14 15:23 UTC, TomAFrench commented
Closing after discussing with Michael

2024-06-14 15:23 UTC, closed without merging