feat: Separate runtimes of SSA functions before inlining
noir-lang/noir pull request #5121
Opened 2024-05-28 10:40 UTC by sirasistant

# Description

## Problem\*

Resolves https://github.com/noir-lang/noir/issues/5043

<details>
<summary>Opcode count of Aztec public functions before => after this change in the inlining strategy</summary>

```
_approve_bridge_and_exit_input_asset_to_L1 on contract Uniswap with size 3788 => 3166
_assert_token_is_same on contract TokenBridge with size 916 => 640
_assert_token_is_same on contract Uniswap with size 1845 => 1546
_borrow on contract Lending with size 10988 => 10152
_call_mint_on_token on contract TokenBridge with size 1427 => 1125
_check_deadline on contract Crowdfunding with size 1015 => 752
_deposit on contract Lending with size 1699 => 1220
_increase_public_balance on contract GasToken with size 1325 => 1103
_increase_public_balance on contract Token with size 1577 => 1201
_increase_public_balance on contract TokenBlacklist with size 1577 => 1201
_reduce_total_supply on contract Token with size 945 => 626
_reduce_total_supply on contract TokenBlacklist with size 945 => 626
_repay on contract Lending with size 6775 => 6284
_withdraw on contract Lending with size 10715 => 9850
add_args_return on contract AvmNestedCallsTest with size 15 => 15
add_args_return on contract AvmTest with size 15 => 15
add_storage_map on contract AvmTest with size 797 => 664
add_to_tally_public on contract EasyPrivateVoting with size 1496 => 1112
add_u128 on contract AvmTest with size 187 => 187
admin on contract Token with size 495 => 348
approve_public_authwit on contract EcdsaAccount with size 977 => 718
approve_public_authwit on contract SchnorrAccount with size 743 => 621
approve_public_authwit on contract SchnorrHardcodedAccount with size 742 => 620
approve_public_authwit on contract SchnorrSingleKeyAccount with size 742 => 620
assert_block_number on contract AppSubscription with size 920 => 669
assert_minter_and_mint on contract Token with size 1434 => 1035
assert_not_expired on contract AppSubscription with size 910 => 658
assert_nullifier_exists on contract AvmTest with size 242 => 156
assert_public_global_vars on contract Test with size 1054 => 679
assert_same on contract AvmNestedCallsTest with size 138 => 138
assert_unsiloed_nullifier_acvm on contract AvmAcvmInteropTest with size 102 => 16
assertion_failure on contract AvmTest with size 166 => 166
avm_to_acvm_call on contract AvmAcvmInteropTest with size 287 => 169
balance_of_public on contract GasToken with size 651 => 612
balance_of_public on contract Token with size 880 => 710
balance_of_public on contract TokenBlacklist with size 880 => 710
borrow_public on contract Lending with size 1193 => 939
broadcast on contract Benchmarking with size 419 => 337
burn_public on contract Token with size 2426 => 1962
burn_public on contract TokenBlacklist with size 3148 => 2468
call_acvm_from_avm on contract AvmAcvmInteropTest with size 574 => 503
call_avm_from_acvm on contract AvmAcvmInteropTest with size 578 => 507
check_balance on contract GasToken with size 856 => 768
check_selector on contract AvmTest with size 463 => 463
claim_public on contract GasToken with size 3963 => 3416
claim_public on contract TokenBridge with size 4176 => 3457
constant_field_acvm on contract AvmAcvmInteropTest with size 13 => 13
constant_field_avm on contract AvmAcvmInteropTest with size 13 => 13
constructor on contract AppSubscription with size 3376 => 1983
constructor on contract Auth with size 1414 => 994
constructor on contract AvmInitializerTest with size 1290 => 908
constructor on contract Claim with size 1700 => 1123
constructor on contract EasyPrivateVoting with size 1454 => 941
constructor on contract FPC with size 1700 => 1123
constructor on contract InclusionProofs with size 1021 => 704
constructor on contract Token with size 2737 => 1961
constructor on contract TokenBlacklist with size 1925 => 1285
constructor on contract TokenBridge with size 1400 => 924
constructor on contract Uniswap with size 1326 => 909
consume_message_from_arbitrary_sender_public on contract Test with size 2203 => 1893
consume_mint_public_message on contract Test with size 2910 => 2600
create_different_nullifier_in_nested_call on contract AvmNestedCallsTest with size 743 => 639
create_l2_to_l1_message_arbitrary_recipient_public on contract Test with size 56 => 12
create_l2_to_l1_message_public on contract Test with size 73 => 29
create_same_nullifier_in_nested_call on contract AvmNestedCallsTest with size 741 => 637
debug_logging on contract AvmTest with size 725 => 402
deposit_public on contract Lending with size 2286 => 1846
dummy_public_call on contract Test with size 354 => 284
emit_nullifier_and_check on contract AvmTest with size 436 => 314
emit_nullifier_public on contract Test with size 47 => 11
emit_unencrypted on contract Test with size 54 => 16
emit_unencrypted_log on contract AvmTest with size 757 => 685
end_vote on contract EasyPrivateVoting with size 514 => 279
exit_to_l1_public on contract TokenBridge with size 2154 => 1773
get_address on contract AvmTest with size 45 => 13
get_args_hash on contract AvmTest with size 18 => 18
get_asset on contract Lending with size 888 => 718
get_assets on contract Lending with size 587 => 411
get_authorized on contract Auth with size 597 => 443
get_authorized_delay on contract Auth with size 702 => 517
get_block_number on contract AvmTest with size 45 => 13
get_chain_id on contract AvmTest with size 45 => 13
get_fee_per_da_gas on contract AvmTest with size 45 => 13
get_fee_per_l2_gas on contract AvmTest with size 45 => 13
get_portal_address_public on contract TokenBridge with size 297 => 145
get_position on contract Lending with size 3908 => 3623
get_price on contract PriceFeed with size 617 => 579
get_public_value on contract StatefulTest with size 636 => 598
get_roles on contract TokenBlacklist with size 989 => 749
get_scheduled_authorized on contract Auth with size 595 => 443
get_sender on contract AvmTest with size 45 => 13
get_shared_immutable_constrained_public on contract DocsExample with size 438 => 406
get_shared_immutable_constrained_public_indirect on contract DocsExample with size 701 => 607
get_shared_immutable_constrained_public_multiple on contract DocsExample with size 136 => 98
get_storage_address on contract AvmTest with size 45 => 13
get_timestamp on contract AvmTest with size 45 => 13
get_token on contract TokenBridge with size 513 => 366
get_transaction_fee on contract AvmTest with size 45 => 13
get_version on contract AvmTest with size 45 => 13
increment_balance on contract Benchmarking with size 1472 => 1264
increment_public_value on contract StatefulTest with size 695 => 449
increment_public_value_no_init_check on contract StatefulTest with size 447 => 351
init on contract Crowdfunding with size 2100 => 1341
init on contract Lending with size 958 => 598
initialize_public_immutable on contract DocsExample with size 433 => 252
initialize_shared_immutable on contract DocsExample with size 433 => 252
is_minter on contract Token with size 838 => 668
is_time_equal on contract Test with size 56 => 18
keccak_hash on contract AvmTest with size 49 => 49
l1_to_l2_msg_exists on contract AvmTest with size 65 => 17
mint_private on contract Token with size 1247 => 790
mint_private on contract TokenBlacklist with size 1495 => 906
mint_public on contract GasToken with size 946 => 813
mint_public on contract Token with size 2048 => 1520
mint_public on contract TokenBlacklist with size 2821 => 2137
modulo2 on contract AvmTest with size 16 => 16
nested_call_to_add on contract AvmNestedCallsTest with size 862 => 756
nested_call_to_add_with_gas on contract AvmNestedCallsTest with size 929 => 799
nested_static_call_to_add on contract AvmNestedCallsTest with size 890 => 784
nested_static_call_to_set_storage on contract AvmNestedCallsTest with size 759 => 665
new_note_hash on contract AvmTest with size 47 => 11
new_nullifier on contract AvmAcvmInteropTest with size 47 => 11
new_nullifier on contract AvmNestedCallsTest with size 47 => 11
new_nullifier on contract AvmTest with size 47 => 11
new_n [...]

2024-05-28 20:56 UTC, jfecher requested changes
Didn't have enough time to finish the review today so I'm blocking this to give me more time to think on the approach taken tomorrow. I'm wondering if we can avoid the extra pass at all and whether we can avoid the extra passes through the IR that are now within the inlining pass to look for recursive functions and functions that can be inlined.

For now, there's just a few nitpicks:

2024-05-28 20:56 UTC, jfecher commented on compiler/noirc_evaluator/src/ssa/opt/inlining.rs
> +use im::HashSet as ImmutableHashSet;
```suggestion
```
Might as well refer to this as `im::HashSet` - it is shorter and avoids having different names for the same thing across the codebase.

2024-05-28 20:56 UTC, jfecher commented on compiler/noirc_evaluator/src/ssa/opt/inlining.rs
> +    let brillig_entry_points: BTreeSet<_> = ssa
Let's combine this with the acir_entry_points loop below to avoid looping twice. If it's easier we can change it to a for loop instead

2024-05-29 07:07 UTC, sirasistant commented on acvm-repo/brillig_vm/src/memory.rs
> +        }
Yep! When allocating a zero length array we just copy the free memory pointer to the array pointer, but we don't write any items, so the memory does not expand up to the index pointed by the array. When passing the array to a foreign call, the foreign call tries to use read slice to read the array, and read slice will fail if the pointer is past initialized memory, even though it's length zero. Ideally we'd make read slice aligned with read https://github.com/noir-lang/noir/blob/d5449fc8b14557a26bf36f683dc5a535f2ad1ee9/acvm-repo/brillig_vm/src/memory.rs#L289 where it allows reading uninitialized memory by returning a default value, but then we wouldn't be able to return a slice, we'd have to return owned data.

2024-05-29 07:15 UTC, sirasistant commented
>  I'm wondering if we can avoid the extra pass at all and whether we can avoid the extra passes through the IR that are now within the inlining pass to look for recursive functions and functions that can be inlined.

I think it can be avoided, but then the inlining step becomes footgun land:
 - In order to find brillig entry points, it has to explore recursively the SSA, instead of just searching for acir functions that call brillig
 - Recursive functions in the SSA could marked as ACIR but called from brillig. This approach correctly handles this case, but without the runtime separation pass it'll try to unroll the recursive function even in a brillig context, so it'll need to clone the recursive function to brillig.

In general I think it's saner to have a pass that makes the function.runtime express what the function will actually be converted to and reduce the inliner responsibility to just inline functions instead of dealing with context-dependant runtimes. And even if we don't have the pass the inliner will have to do most of the pass work so I think it's cleaner to have it in a separate pass with clear responsibilities.

2024-05-29 07:43 UTC, sirasistant commented on acvm-repo/brillig_vm/src/memory.rs
> +        }
Added a comment

2024-05-29 07:48 UTC, sirasistant commented
> Recursive functions in the SSA could marked as ACIR but called from brillig. This approach correctly handles this case, but without the runtime separation pass it'll try to unroll the recursive function even in a brillig context, so it'll need to clone the recursive function to brillig. Let me add an e2e test case for this.

Added the e2e test case that fails on nightly and is fixed by this process.

2024-05-29 11:39 UTC, TomAFrench commented
I'm in favour of having this as a separate pass for simplicity and ease of testing. If necessary those two passes can be merged in future.

2024-05-29 14:26 UTC, sirasistant commented
Possibly the passes that run after unrolling are the ones that have more impact, since unrolling (logically) tends to increase a lot instruction counts

2024-05-29 14:27 UTC, sirasistant commented
I thought about making this pass more lightweight via collecting called functions using func.values_iter(), but I think it makes it way more brittle, since we could have unused function values there ):

2024-05-29 14:32 UTC, sirasistant commented
If performance of this pass is a concern I can possibly explore the SSA only once and build a cache of functionId => calledFunctionIds to be reused across the pass. But I'm not sure it'll make much of a difference

2024-05-29 14:58 UTC, sirasistant commented
Nah, it won't be much of a difference because we do need to reexplore to trim unreachable functions anyway

2024-05-29 15:10 UTC, jfecher commented
Yeah, I didn't see the cache making much of a difference either.
Anyway - the main reason I blocked this yesterday was to give me more time to review today not that I didn't think this should be merged. I'll finish the review now

2024-05-29 15:42 UTC, jfecher reviewed
LGTM. Just some final nitpicks

2024-05-29 15:42 UTC, jfecher commented on compiler/noirc_evaluator/src/ssa/opt/inlining.rs
> +                            };
Can you break this out into a helper function called `should_inline_call` or similar? I think it's getting large enough now that it'd simplify reading `inline_block_instructions` if it were cut out

2024-05-29 15:42 UTC, jfecher commented on compiler/noirc_evaluator/src/ssa/opt/runtime_separation.rs
> +
```suggestion
```

2024-05-29 15:42 UTC, jfecher commented on compiler/noirc_evaluator/src/ssa/opt/runtime_separation.rs
> +                    ssa.functions.get(called_func_id).expect("Function should exist in SSA");
```suggestion
                let called_func = &ssa.functions[called_func_id];
```
Nitpick: we do this in a few places but I don't think the expect message adds much here

2024-05-29 16:27 UTC, jfecher approved these changes

2024-05-29 16:54 UTC, sirasistant commented
Still no permission to add to merge queue ): @TomAFrench

2024-05-29 17:05 UTC, merged