fix(experimental elaborator): Fix globals which use function calls
noir-lang/noir pull request #5172
Opened 2024-06-04 17:38 UTC by jfecher

# Description

## Problem\*

Resolves an issue where we would give a type error if a global ever used a function call in its definition.

## Summary\*

This one was more difficult to fix than it seemed since fixing the main bug revealed progressively more bugs.

## Additional Context

https://github.com/noir-lang/noir/pull/5170 is included here as well to help me see that all tests are now passing.

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

2024-06-04 17:41 UTC, jfecher commented
I messed up something in the merge with master since I'm getting a lot of the following errors now:
```
misplaced #[no_predicates] attribute on unconstrained function basic_checks. Only allowed on constrained functions
```
Will fix tomorrow.

2024-06-05 11:02 UTC, michaeljklein requested changes

2024-06-05 11:09 UTC, jfecher commented on compiler/noirc_frontend/src/tests.rs
> +            true,
This was part of the CI changes to test the elaborator. Unfortunately for the frontend tests I couldn't easily test the elaborator and the existing frontend without duplicating them all. I changed them to only use the elaborator here but can change it back if we'd prefer that.

2024-06-05 11:11 UTC, michaeljklein commented on compiler/noirc_frontend/src/tests.rs
> +            true,
Yes, please keep the normal tests on for now.

2024-06-05 11:12 UTC, jfecher commented on compiler/noirc_frontend/src/tests.rs
> +            true,
Reverted

2024-06-05 16:46 UTC, merged