feat: Run `comptime` code from annotations on a type definition
noir-lang/noir pull request #5256
Opened 2024-06-14 21:07 UTC by jfecher

# Description

## Problem\*

Resolves https://github.com/noir-lang/noir/issues/5255

## Summary\*

Implements the ability to run comptime code when an annotation is put on a type definition. This annotation must resolve to a comptime function in scope, which is then called with the type definition as an argument. There are currently no API functions to actually do anything with a `TypeDefinition` object. The plan is to add functions in the future to inspect or add fields & generics.

```rs
#[print_type]
struct Foo {
    bar: Field,
}

comptime fn print_type(typ: TypeDefinition) {
    println("hello from print_type_name at compile-time");
    println(typ); // only prints "(type definition)" currently
}

fn main(){}
```

## Additional Context

## Documentation\*

Check one:
- [ ] No documentation needed.
- [ ] Documentation included in this PR.
- [x] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

2024-06-17 18:15 UTC, jfecher commented
Had to remove the integration test. Printing at compile-time breaks the formatting of the outputted JSON when generating tests

2024-06-17 20:32 UTC, michaeljklein requested changes
LGTM

Can you add a basic test for this, e.g. running an identity function over the definition?

2024-06-17 20:35 UTC, jfecher commented
@michaeljklein I had one before, but without the printout there's no way to verify the function actually ran. I suppose the only thing you'd see is the lack of a warning

2024-06-17 20:56 UTC, jfecher commented
Ok, I added a test case. I test the function is run by failing an assertion only within the function and adding it to the compile failure tests.

2024-06-18 17:12 UTC, michaeljklein approved these changes

2024-06-18 17:41 UTC, merged