fix: `NoMatchingImplFound` in comptime code only
noir-lang/noir pull request #5617
Opened 2024-07-26 19:53 UTC by jfecher

# Description

## Problem\*

Resolves #5615

## Summary\*

Fixes a difference in how the interpreter and monomorphizer handle generics - further explained in the linked issue.

## Additional Context

To fix this I saved the generics on each link in the call stack and restored them after the function finishes. This wasn't good enough however - doing this too early mean losing intermediate bindings in `instantiation_bindings`. So I needed to add some `follow_bindings` there as well. The `impl_bindings` all bind the trait impl to the trait itself so follow_bindings there is unneeded.

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

2024-07-26 20:17 UTC, michaeljklein requested changes
LGTM besides the leftover `dbg`

2024-07-26 20:17 UTC, michaeljklein commented on compiler/noirc_frontend/src/monomorphization/mod.rs
> +                    dbg!(&constraints);
leftover `dbg`

2024-07-26 20:31 UTC, jfecher commented on compiler/noirc_frontend/src/monomorphization/mod.rs
> +                    dbg!(&constraints);
Oops, fixed.

2024-07-29 13:13 UTC, michaeljklein approved these changes

2024-07-29 13:22 UTC, merged