feat: don't eagerly error on cast expressions
noir-lang/noir pull request #5635
Opened 2024-07-30 15:36 UTC by asterite

# Description

## Problem\*

Resolves #4994

## Summary\*

## Additional Context

## Documentation\*

Check one:
- [ ] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

2024-07-30 21:03 UTC, jfecher requested changes
I'm really not sure that this case is important enough to merit a new type variable kind.

I think for now we can just bind to an IntegerOrField and users will need a type annotation if they wanted a boolean.

2024-07-30 21:03 UTC, jfecher commented on compiler/noirc_frontend/src/elaborator/types.rs
> +                }
This shouldn't be reachable since `follow_bindings` is called

2024-07-30 21:03 UTC, jfecher commented on compiler/noirc_frontend/src/hir_def/types.rs
> +    Polymorphic(PolymorphicKind),
All type variables are polymorphic so this is a misnomer

2024-07-30 21:03 UTC, jfecher commented on compiler/noirc_frontend/src/hir_def/types.rs
> +    Constant(u32),
Unrelated to this PR: I think this variant is unused. I should make an issue for removing it.

2024-07-31 11:08 UTC, asterite commented
> I think for now we can just bind to an IntegerOrField and users will need a type annotation if they wanted a boolean.

Makes sense. I tried to do the most correct thing but I also wondered if it wasn't too much to add this new type just for this use case. In any case it helped me continue the tour over the code base :-)

2024-07-31 15:30 UTC, jfecher approved these changes

2024-07-31 15:30 UTC, jfecher commented on compiler/noirc_frontend/src/elaborator/types.rs
> +                self.unify(from, expected, || TypeCheckError::InvalidCast {
```suggestion
                let expected = Type::polymorphic_integer_or_field(self.interner);
                self.unify(from, &expected, || TypeCheckError::InvalidCast {
```
One two many references

2024-07-31 15:59 UTC, merged