fix: Handle multi-byte utf8 characters in formatter
noir-lang/noir pull request #6118
Opened 2024-09-20 18:14 UTC by jfecher

# Description

## Problem\*

Resolves https://github.com/noir-lang/noir/issues/6108

## Summary\*

## Additional Context

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

2024-09-20 18:21 UTC, vezenovm approved these changes
LGTM can we just add some of these characters to one of the fmt tests?

2024-09-20 20:43 UTC, michaeljklein requested changes
Our lexer currently prevents any characters besides ASCII in code: I would expect comments to be ASCII-only as well.

2024-09-23 16:37 UTC, michaeljklein approved these changes
Added a lexer error for non-ASCII comments

2024-09-23 18:04 UTC, asterite approved these changes

2024-09-24 19:01 UTC, merged