feat(perf): Simplify array get when most recent array set writes to the same index
noir-lang/noir pull request #6220
Opened 2024-10-03 18:43 UTC by vezenovm

… the same index

# Description

## Problem\*

Part of general effort to reduce Brillig bytecode sizes

## Summary\*

## Additional Context

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

2024-10-04 00:03 UTC, michaeljklein approved these changes

2024-10-04 09:21 UTC, TomAFrench requested changes
I don't think this takes into account `enable_side_effects`. Can you add a test for this?

```
fn main(v1: [Field; 3], v2: u32) {
   enable_side_effects u1 0
   v4 = array_set v1, index v2, value v3
   enable_side_effects u1 1
   v5 = array_get v4, index v2
   return v5
}
```

2024-10-04 15:34 UTC, vezenovm commented
> I don't think this takes into account `enable_side_effects`

Ah yes good catch. I'm not sure if we can have this optimization here then as we need more information than just the array instructions. Going to convert this back to a draft for now.

2024-12-02 20:02 UTC, vezenovm commented
Closing in favor of https://github.com/noir-lang/noir/pull/6684 which takes side effects into account

2024-12-02 20:02 UTC, closed without merging