Use published acvm v0.1.0
noir-lang/noir pull request #623
Opened 2023-01-09 23:46 UTC by phated

# Related issue(s)

Resolves #596 

# Description

## Summary of changes

This PR swaps out the `avcm` dependency from the noir-lang/noir repo for the v0.1.0 version published on crates.io - The 0.1.0 version should be compatible with the current version of noir, but it is published from a separate repository.

## Dependency additions / changes

The published `acvm` crate.

## Test additions / changes

N/A

# Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [x] I have reviewed the changes on GitHub, line by line.
- [x] I have ensured all changes are covered in the description.

# Additional context

This PR is needed in combination with https://github.com/noir-lang/aztec_backend/pull/36 to successfully install nargo with a completely fresh clone.

2023-01-10 10:40 UTC, guipublic requested changes
Before switching to the new acvm, we should first:
merge current PRs that modify acvm
review the new acvm changes
update the new acvm with the internal acvm

2023-01-10 19:44 UTC, phated commented
Now that I have that native backend building on Mac, I tried to see debug the CI problems locally and none of them appear when I run `cargo check` and `cargo clippy` 🤔

2023-01-10 21:31 UTC, phated commented
I had not updated the lockfile, so I tried doing that. It still points at some acir and acvm github references (assumed from the dep graph)

2023-01-18 23:35 UTC, phated commented
Replaced by #647

2023-01-18 23:35 UTC, closed without merging