feat: error if generic type parameter in impl is not mentioned in self type
noir-lang/noir pull request #6388
Opened 2024-10-29 15:28 UTC by asterite

# Description

## Problem

Resolves #5855

## Summary

I decided to do this check separately... that is, another way could have been to keep track of which generics we saw while we solve `self_type`, but I think that would lead to code that's harder to understand. I was also able to use the visitor pattern to quickly find the mentioned generic types (I had to update Visitor so that it correctly traverses unresolved type expressions).

## Additional Context

Some questions:
1. We only produce this error for `impl`... do we also want to do it for trait impls? If yes, in this PR or a separate one?
2. Should we use the same error message as Rust? I find it a bit hard to understand, although it kind of makes sense. Let me know!

## Documentation

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

2025-04-01 17:56 UTC, michaeljklein requested changes
LGTM, but please add a test that uses a numeric generic as in the original issue, e.g. similar to the one I suggested (untested).

> We only produce this error for `impl...` do we also want to do it for trait impls? If yes, in this PR or a separate one?

Yes, I think we also want this error for trait impls and a separate PR would be fine

> Should we use the same error message as Rust? I find it a bit hard to understand, although it kind of makes sense. Let me know!

I think the current error is clear

2025-04-01 17:56 UTC, michaeljklein commented on compiler/noirc_frontend/src/tests.rs
> +}
Simplified form of the original failing case:

```suggestion
}

#[test]
fn unconstrained_numeric_generic_in_impl() {
    let src = r#"
        pub struct Foo {}
        impl<let N: u32> Foo {}
                 ^ The type parameter `N` is not constrained by the impl trait, self type, or predicates
                 ~ Hint: remove the `N` type parameter
        fn main() {
            let _ = Foo {};
        }
        "#;
    check_errors(src);
}
```

2025-04-01 18:04 UTC, asterite commented on compiler/noirc_frontend/src/tests.rs
> +}
Done!

2025-04-02 19:41 UTC, michaeljklein approved these changes

2025-04-02 20:39 UTC, merged