feat(ssa): Bring tracking of RC instructions during DIE
noir-lang/noir pull request #6783
Opened 2024-12-12 03:52 UTC by vezenovm

…unt for calls

# Description

## Problem\*

Resolves 

## Summary\*

Currently a draft as I just want to see bench reports to start. This came to mind while working on https://github.com/noir-lang/noir/pull/6782 as actually being a very beneficial optimization. After #6782 we will have multiple locations (loop invariant code motion and constant folding) where upon moving a make_array instructions, we will conservatively issue inc_rc instructions in case that array is mutable. However, if the array is never mutated or mutably borrowed that will lead to us unnecessary incrementing the reference counter. 

## Additional Context

## Documentation\*

Check one:
- [ ] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

2024-12-12 15:07 UTC, jfecher commented
Maybe it'd be easier if we promote this to its own pass rather than basing it off of DIE logic

2024-12-12 15:33 UTC, vezenovm commented
> Maybe it'd be easier if we promote this to its own pass rather than basing it off of DIE logic

Perhaps, I was thinking the same thing as it makes DIE more complex. On the flip side, I wanted to avoid another pass for this logic which can be contained to DIE and in a way does remove useless instructions (even if they are not "dead").

2024-12-12 20:06 UTC, vezenovm commented on compiler/noirc_evaluator/src/ssa/opt/die.rs
> +    // If an array has not been mutably borrowed we can then safely remove all IncrementRc instructions on that array.
```suggestion
    // We also separately track all IncrementRc instructions and all array types which have been mutably borrowed.
    // If an array is the same type as one of those non-mutated array types, we can safely remove all IncrementRc instructions on that array.
```

2024-12-12 20:21 UTC, jfecher requested changes
I'd like to see if this breaks an external repos if we change rcs to start at 1 again instead of 2. No errors in cargo test locally at least, but I'm checking in https://github.com/noir-lang/noir/pull/6797 in the meantime.

2024-12-12 22:06 UTC, vezenovm commented
> **regression_4709**	-51,320,073 ✅	**-97.72%**

This PR is where we get the largest benefit for patterns like this test where we are simply reading from a global array in a loop.

2024-12-13 13:36 UTC, jfecher commented
My main hesitancy with this PR is that it was removed for correctness before and is re-added now but what changed? As far as I can tell it's identical. Won't we run into sync issues again? Or run into them once https://github.com/noir-lang/noir/pull/6797 is added as well?

2024-12-13 15:38 UTC, vezenovm commented
> My main hesitancy with this PR is that it was removed for correctness before and is re-added now but what changed? As far as I can tell it's identical. Won't we run into sync issues again? Or run into them once #6797 is added as well?

This PR also adds a check for whether an array type was passed to a call. I have also tested it here (https://github.com/AztecProtocol/aztec-packages/pull/10399) which passes all noir-projects tests in atec-packages (the yarn-project-test failures look to be from the p2p network tests). 

It does look this PR would run into issues with #6797. But don't we have these issues already if we were to add back #6797?

2024-12-13 16:32 UTC, jfecher approved these changes
Hmm alright, I'm okay with merging this then. Are you confident passing arrays into calls was the original issue or is this something we should continue investigating?

> It does look this PR would run into issues with https://github.com/noir-lang/noir/pull/6797. But don't we have these issues already if we were to add back https://github.com/noir-lang/noir/pull/6797?

I'm not concerned with #6797, the only failure there was from the failure that was originally specific to that rc change rather than the RcTracker changes here.

2024-12-13 16:52 UTC, vezenovm commented
> Hmm alright, I'm okay with merging this then. Are you confident passing arrays into calls was the original issue or is this something we should continue investigating?

Working with the original RC tracker (no `Call` checks), I had not finished reproducing the error from the noir protocol circuits failure yet. I then decided to try things against the `reference_counts` test with different inlining settings. We were hitting the case where `copy_mut` was failing as `array` was not being incremented as expected. This made sense to me as I was already thinking we need to treat `Call` the same way we treat `Store` for checking non mutated arrays. The failure from `reference_counts` is the one laid out in the `do_not_remove_inc_rc_if_used_as_call_arg` unit test (one of the only other new things in this PR). 

I can continue trying to reproduce the exact Noir snippet from aztec-packages, but I do think not checking arrays passed to calls was the culprit of the broken RC tracker.

2024-12-13 17:16 UTC, merged