chore: Release Noir(1.0.0-beta.2)
noir-lang/noir pull request #6914
Opened 2024-12-23 16:08 UTC by noirwhal

:robot: I have created a release *beep* *boop*
---

## [1.0.0-beta.2](https://github.com/noir-lang/noir/compare/v1.0.0-beta.1...v1.0.0-beta.2) (2024-12-23)

### Bug Fixes

* Remove unnecessary cast in bit-shift ([#6890](https://github.com/noir-lang/noir/issues/6890)) ([011fbc1](https://github.com/noir-lang/noir/commit/011fbc195419df0254af69cfea593291c8f80af3))

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

2025-01-13 20:33 UTC, Savio-Sou approved these changes

2025-01-13 20:34 UTC, TomAFrench requested changes
bugs in here which cause issues for critical libs.

2025-02-10 14:27 UTC, TomAFrench approved these changes

2025-02-10 15:05 UTC, merged

2025-02-10 15:05 UTC, noirwhal commented
:robot: Created releases:
- [v1.0.0-beta.2](https://github.com/noir-lang/noir/releases/tag/v1.0.0-beta.2)
:sunflower: